// Exports each contract's ABI from the Foundry `out/` dir into web/lib/abis.ts,
// so the frontend always tracks the real compiled on-chain interface (no hand-maintained drift).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../../contracts/out");
const libPath = resolve(here, "../lib/abis.ts");

const names = ["MockMXNB", "ReputationSBT", "Underwriter", "InsurancePool", "CircleFactory", "TandaCircle"];

const blocks = names.map((n) => {
  const json = JSON.parse(readFileSync(resolve(outDir, `${n}.sol/${n}.json`), "utf8"));
  return `export const ${n}_ABI = ${JSON.stringify(json.abi)} as const;`;
});

mkdirSync(dirname(libPath), { recursive: true });
writeFileSync(libPath, "// AUTO-GENERATED by scripts/export-abis.mjs — do not edit by hand.\n" + blocks.join("\n\n") + "\n");
console.log(`wrote ${libPath} (${names.length} ABIs)`);
